name: Desplegar Infraestructura AWS

on:
  push:
    branches: [main]

jobs:
  terraform_deploy:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: us-east-1 

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
          
      - name: Inicializar Terraform
        run: terraform init

      - name: Verificar formato Terraform
        run: terraform fmt -check -recursive

      - name: Validar configuración Terraform
        run: terraform validate

      - name: Aplicar infraestructura Terraform
        run: terraform apply -auto-approve
