name: Desplegar Infraestructura + Subir CSVs

on:
  push:
    branches: [main]
    paths:
      - 'csv/**'
      - '**.tf'
      - '.github/workflows/main.yml'
      - 'src/**'

env:
  AWS_REGION: us-east-1

jobs:
  deploy_and_upload:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Inicializar Terraform
        run: terraform init

      - name: Aplicar configuración de Terraform
        run: terraform apply -auto-approve

      - name: Obtener nombre del bucket de entrada
        id: get_outputs
        run: |
          echo "INPUT_BUCKET_NAME=$(terraform output -raw input_bucket_name)" >> $GITHUB_ENV

      - name: Instalar dependencias Python
        run: pip install -r src/requirements.txt

      - name: Subir archivos CSV a S3
        env:
          INPUT_BUCKET_NAME: ${{ env.INPUT_BUCKET_NAME }}
        run: python src/upload_csv.py
