name: Subir CSVs al bucket

on:
  push:
    branches: [main]
    paths:
      - 'csv/**'

jobs:
  upload_csv:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: us-east-1   # 👈 Se define aquí para todos los pasos

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Inicializar Terraform
        run: terraform init

      - name: Obtener outputs de Terraform
        id: get_outputs
        run: |
          echo "INPUT_BUCKET_NAME=$(terraform output -raw input_bucket_name)" >> $GITHUB_ENV

      - name: Instalar dependencias Python
        run: pip install -r src/requirements.txt

      - name: Configurar AWS
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Ejecutar script para subir CSVs
        env:
          INPUT_BUCKET_NAME: ${{ env.INPUT_BUCKET_NAME }}
        run: python src/upload_csv.py
